// All 18 maps from the spreadsheet. Ratings inferred from your comments — tweak in the UI.
// Rating scale: 4 = best maps, 3 = hype, 2 = fine, 1 = could've done it better
window.MAPS_DATA = [
  {
    id: 1,
    mod: "HD2",
    title: "G.O.A.T.",
    artist: "Polyphia",
    tournament: "Tayqa Cup 2",
    comment: "первый тест маппинга на турниры",
    rating: 2,
  },
  {
    id: 2,
    mod: "NM4",
    title: "Melancolie",
    artist: "LemKuuja",
    tournament: "Garage Cup",
    comment: "лучший экспириенс в моей жизни",
    rating: 4,
  },
  {
    id: 3,
    mod: "NM3",
    title: "Moscow Never Sleeps",
    artist: "DJ Smash",
    tournament: "Russian Provincial Cup 2024",
    comment: "просто ремапнул чутьчуть",
    rating: 2,
  },
  {
    id: 4,
    mod: "FM3",
    title: "disperagioia",
    artist: "gmtn. (witch's slave)",
    tournament: "osu!kz Community Cup 5",
    comment: "чут двигали дохуя, не оч нравится она мне",
    rating: 1,
  },
  {
    id: 5,
    mod: "FM3",
    title: "Reikou Hatsuden",
    artist: "-45",
    tournament: "Ultra Gimmick Hidden Cup",
    comment: "нет слов",
    rating: 3,
  },
  {
    id: 6,
    mod: "HD3",
    title: "black is the new black",
    artist: "goreshit",
    tournament: "Ardub's Rhythmic Draft Ultra Battle",
    comment: "это все забанили, но мне оч нрав",
    rating: 3,
  },
  {
    id: 7,
    mod: "NM4",
    title: "Angel's Salad",
    artist: "katagiri",
    tournament: "Mangal Tournament",
    comment: "лучшая турнирная карта которую я делал",
    rating: 4,
  },
  {
    id: 8,
    mod: "HD2",
    title: "Rainy Boots",
    artist: "Inabakumori",
    tournament: "Double Carry Showdown",
    comment: "ПОДВИГАЛ НОТЫ",
    rating: 2,
  },
  {
    id: 9,
    mod: "HD2",
    title: "Guess feat. Billie Eilish",
    artist: "Charli xcx",
    tournament: "Double Carry Showdown",
    comment: "прикольная, но не возбуждает",
    rating: 2,
  },
  {
    id: 10,
    mod: "DT2",
    title: "Vse proigrali",
    artist: "Yozhik",
    tournament: "Osu! Emo Cup",
    comment: "первая дтшка, получилась няшно",
    rating: 3,
  },
  {
    id: 11,
    mod: "HD8",
    title: "Resonant Harmony",
    artist: "HudsonLee & GMDeXpwn",
    tournament: "Ultra Gimmick Hidden Cup 2",
    comment: "ебать я сру в редактор",
    rating: 1,
  },
  {
    id: 12,
    mod: "HD2",
    title: "Watashi no Nanatsu no Oiwai ni",
    artist: "masa",
    tournament: "6WC 2025",
    comment: "ребятки добрие сидят там",
    rating: 3,
  },
  {
    id: 13,
    mod: "NM6",
    title: "YURUSHITE",
    artist: "t+pazolite",
    tournament: "osu!kz Community Cup 6",
    comment: "хейтрейд",
    rating: 1,
  },
  {
    id: 14,
    mod: "TB",
    title: "Quantielectromolecularifeline Tunnelling",
    artist: "Kou!",
    tournament: "minimalistic cup",
    comment: "коллаборашка",
    rating: 3,
  },
  {
    id: 15,
    mod: "NM2",
    title: "Blue Grotto",
    artist: "Ujico*",
    tournament: "DACH Open",
    comment: "спасибо что разрешили замапать хуйню <3",
    rating: 2,
  },
  {
    id: 16,
    mod: "NM4",
    title: "Heat abnormal",
    artist: "nolsei_01",
    tournament: "MSU Cyberfest osu! cup 2025",
    comment: "мгм уииууиуаиуиаиаиуу",
    rating: 3,
  },
  {
    id: 17,
    mod: "NM7",
    title: "literal legend",
    artist: "ayesha erotica",
    tournament: "Aim Control Heaven",
    comment: "коллаборашка с няшкой кай ангел",
    rating: 4,
  },
  {
    id: 18,
    mod: "DT4",
    title: "Partymaker",
    artist: "Pika",
    tournament: "ПИВОКАП))))))",
    comment: "залупа ебаная для тупорылых",
    rating: 1,
  },
];
